### ISSUE TITLE
By default, all endpoints with envelope pagination should return 50 results

### ISSUE THREAD

**Issue by himynamesdave** [muchdogesec/arango_taxii_server#10]
```
curl -X 'GET' \
  'http://127.0.0.1:8000/api/taxii2/arango_taxii_server_tests_database/collections/mitre_attack_enterprise/objects/?limit=10' \
  -H 'accept: application/taxii+json' \
  -H 'Authorization: Basic XXX'
  ```

It currently returns 1000 (the default arangodb limit) should return 50

**Comment by himynamesdave** [comment]
@fqrious it seems 100 results are now being returned in the payloads (when >100 results found).

Can you show me where envelope response size is defined?

100 results is fine, I just want to log in this ticket where this results limit is defined.

**Comment by fqrious** [comment]
`DEFAULT_PAGINATION_LIMIT` in `arango_taxii_server/settings`
