### ISSUE TITLE
Only the latest version of the objects should be returned by endpoints get objects endpoints

### ISSUE THREAD

**Issue by himynamesdave** [muchdogesec/arango_taxii_server#13]
```
    {"endpoint": f"/api/taxii2/{API_ROOT}/collections/{{COLLECTION_ID}}/objects/", "method": "GET"},
    {"endpoint": f"/api/taxii2/{API_ROOT}/collections/{{COLLECTION_ID}}/manifest/", "method": "GET"},
    {"endpoint": f"/api/taxii2/{API_ROOT}/collections/{{COLLECTION_ID}}/objects/{{OBJECT_ID}}/", "method": "GET"},
```

The user can use the `match[version]` to get specific versions, but by default, if not values set for `match[version]`, theses endpoint should only return the latest objects (`_is_latest==true`)

**Comment by himynamesdave** [comment]
Tested on:

* manifest: passes
* objects: fails (https://www.awesomescreenshot.com/video/29620586?key=678fa1f4c12726edf1e3be717f44de56)
* object/id: passes

**Comment by fqrious** [comment]
should be fixed now
