### ISSUE TITLE
Delete endpoint does not have URL filtering parameters `version` and `spec_version`

### ISSUE THREAD

**Issue by himynamesdave** [muchdogesec/arango_taxii_server#18]
Raised here: https://community.dogesec.com/t/deleting-objects-using-the-arango-taxii-server/84

![image](https://github.com/muchdogesec/arango_taxii_server/assets/1296409/69b73b52-0550-4d17-ac98-6df42e61c97b)

The behaviour should be 

If not parameters passed, ALL objects with the `id` specified deleted.

If parameters passed, only matching object deleted.

**Comment by fqrious** [comment]
cannot reproduce on latest version

**Comment by himynamesdave** [comment]
@fqrious can you make sure these body parameters are also shown in swagger spec

![image](https://github.com/user-attachments/assets/7e7c45ca-f339-456d-a484-0d30cb8ec60b)
