### ISSUE TITLE
Do not pre-populate string items in swagger spec

### ISSUE THREAD

**Issue by himynamesdave** [muchdogesec/arango_taxii_server#32]
https://www.awesomescreenshot.com/video/29620466?key=85a8e74f5f9d77bbc4c77b14a7fb9aac

See when i open the option a default object is shown. Remove these defaults and just show a blank value when user selects.

**Comment by fqrious** [comment]
While I can, I don't think we should because a random value will still be gernerated automatically (from schema definition) by swagger-ui...



![Image](https://github.com/user-attachments/assets/c2195e3d-85bd-41ff-846d-c2821f7e41a8)
