### ISSUE TITLE
`http://127.0.0.1:8000/api/taxii2/<API_ROOT>/` always returns a response

### ISSUE THREAD

**Issue by himynamesdave** [muchdogesec/arango_taxii_server#8]
https://www.awesomescreenshot.com/video/28538962?key=922d4075dbbbc5827c4d959cadc1f3a4

See towards the end of the video I can enter any value for api_root and something will be returned. It should only return valid collections (and user has read or read / write for said collections)

**Comment by fqrious** [comment]
fixed
